name: ico_dart
description: Create, read, and write ICO files with toBytes() and fromBytes() methods.
version: 0.1.0+1
repository: https://github.com/ArinFaraj/ico_maker/tree/main/packages/ico_dart
issue_tracker: https://github.com/ArinFaraj/ico_maker/issues
homepage: https://github.com/ArinFaraj/ico_maker
# documentation: https://arin.at

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

screenshots:
  - description: The ico_dart package logo.
    path: screenshots/logo.png
